#ifndef _LIN_NETWORK_MANAGEMENT_H
#define _LIN_NETWORK_MANAGEMENT_H

#include <stdint.h>

typedef enum
{
    INITIALIZING,
    OPERATIONAL,
    BUS_SLEEP_MODE,
} LIN_Network_State;

typedef enum
{
	LIN_NO_ERROR,
	LIN_SLAVE_ERROR_INVALID_DATA_RX,
	LIN_SLAVE_ERROR_INVALID_CHECKSUM,
	LIN_SLAVE_ERROR_PID_PARITY,
	LIN_SLAVE_ERROR_INVALID_SYNC,
	LIN_SLAVE_ERROR_INVALID_BREAK,
	LIN_SLAVE_ERROR_ID_NOT_FOUND,
	LIN_SLAVE_ERROR_HW_TX,
	LIN_MASTER_ERROR_CHECKSUM,
	LIN_MASTER_ERROR_HEADER_TX,
	LIN_MASTER_ERROR_DATA_TX,
	LIN_MASTER_ERROR_DATA_RX,
	LIN_MASTER_ERROR_DATA_RX_TIMEOUT,
} LIN_Error_Enum_t;


#endif